version: '3'

tasks:
  a-zip:
    cmds:
      - go run main.go archive zip --input sample/archive/input --output sample/archive/output/sample.zip
  e-zip:
    cmds:
      - go run main.go extract zip --input sample/extract/input/sample.zip --output sample/extract/output/
  a-tar:
    cmds:
      - go run main.go archive tar --input sample/archive/input --output sample/archive/output/sample.tar
  e-tar:
    cmds:
      - go run main.go extract tar --input sample/extract/input/sample.tar --output sample/extract/output/
  a-tar-gz:
    cmds:
      - go run main.go archive tar.gz --input sample/archive/input --output sample/archive/output/sample.tar.gz
  e-tar-gz:
    cmds:
      - go run main.go extract tar.gz --input sample/extract/input/sample.tar.gz --output sample/extract/output/
  a-tar-bz2:
    cmds:
      - go run main.go archive tar.bz2 --input sample/archive/input --output sample/archive/output/sample.tar.bz2
