version: '3'

tasks:
  a-zip:
    cmds:
      - go run main.go archive zip --input sample/archive/input --output sample/archive/output/sample.zip
  e-zip:
    cmds:
      - go run main.go extract zip --input sample/extract/input/sample.zip --output sample/extract/output/
  a-tar:
    cmds:
      - go run main.go archive tar --input sample/archive/input --output sample/archive/output/sample.tar